"""Generate shell instrumentation while preserving the job body verbatim."""

from pathlib import Path
import shlex
from typing import Sequence


def _shlex_join(parts: Sequence[str]) -> str:
    # Preserve runtime expansion of ${TMPDIR} in the generated command.
    return " ".join(str(part) if str(part).startswith('${TMPDIR}/')
                    else shlex.quote(str(part)) for part in parts)


def render_instrumented_job(
    parsed: dict, run_script_path: Path, def_out: str,
    singularity_image: str, defcon_exe: Path,
    include: str | None = None, exclude: str | None = None,
    gpu: str = "auto",
    mpi: str = "auto",
    mpi_root: str | None = None,
) -> str:
    """Render a scheduler wrapper; TMPDIR expands when the job executes."""
    trace_file = "${TMPDIR}/defcon_trace.out"
    env_file = "${TMPDIR}/defcon_env.out"
    stage2_cmd = [
        "python3",
        str(defcon_exe),
        "stage2",
        "-t", trace_file,
        "-e", env_file,
        "--command-file", str(run_script_path),
        "-o", def_out,
        "-s", singularity_image,
    ]

    stage2_cmd.extend(["--gpu", gpu])
    stage2_cmd.extend(["--mpi", mpi])
    if mpi_root:
        stage2_cmd.extend(["--mpi-root", mpi_root])

    if include:
        stage2_cmd.extend(["--inc", include])
    if exclude:
        stage2_cmd.extend(["--exc", exclude])

    job_lines = [
        parsed["shebang"],
        "",
        "# === Generated by defcon stage1 — submit this script ===",
        "",
    ] + parsed["directives"] + [
        "",
        "# Capture environment before modules alter it",
        f"env -0 > {env_file}",
        "",
        "# Run original script under strace",
        f"strace -f -e trace=file -s 4096 -o {trace_file} bash {shlex.quote(str(run_script_path))}",
        "",
        "# Automatically generate Singularity definition (DEFCON 1)",
        _shlex_join(stage2_cmd),
    ]
    return "\n".join(job_lines) + "\n"
