"""GPU trace detection and host-runtime integration for NVIDIA and AMD."""

from pathlib import Path
import re
import fnmatch

from strace_parser import ERROR_PATTERNS, PATH_RE

GPU_MODES = ('auto', 'nvidia', 'amd', 'none')
RUNTIME_FLAGS = {'nvidia': '--nv', 'amd': '--rocm'}
# These belong to the allocation where the container runs, not the capture job.
ALLOCATION_VARIABLES = {
    'CUDA_VISIBLE_DEVICES', 'NVIDIA_VISIBLE_DEVICES', 'HIP_VISIBLE_DEVICES',
    'ROCR_VISIBLE_DEVICES', 'GPU_DEVICE_ORDINAL',
}
NVIDIA_LIB_PREFIXES = ('libcudart.', 'libcublas', 'libcudnn', 'libcufft',
                       'libcurand', 'libcusolver', 'libcusparse', 'libnvrtc',
                       'libnvJitLink', 'libnccl.')
AMD_LIB_PREFIXES = ('librocblas.', 'libhiprtc.', 'libMIOpen.', 'librccl.',
                    'librocsparse.', 'librocsolver.')
APPLICATION_LIB_PREFIXES = NVIDIA_LIB_PREFIXES + AMD_LIB_PREFIXES
DRIVER_PATTERNS = ('libcuda.so*', 'libnvidia-*.so*', 'libamdhip64.so*',
                   'libhsa-runtime64.so*', 'libhsakmt.so*')
_TOOLKIT = re.compile(
    r'^(/usr/local/cuda(?:-[^/]+)?|/opt/rocm(?:-[^/]+)?|'
    r'/share/pkg\.[^/]+/(?:cuda|rocm)/[^/]+/install)(?:/|$)'
)


def is_host_driver(path):
    return any(fnmatch.fnmatch(Path(path).name, pattern) for pattern in DRIVER_PATTERNS)


def inspect_trace(trace_path: Path, mode='auto'):
    """Return GPU backends and toolkit roots observed in successful accesses.

    Detection is evidence of a dependency, not proof that GPU work succeeded.
    Explicit modes cover traces that do not expose recognizable GPU paths.
    """
    if mode not in GPU_MODES:
        raise ValueError(f'Unknown GPU mode: {mode}')
    if mode == 'none':
        return [], []
    detected = set()
    roots = set()
    with trace_path.open(errors='ignore') as trace:
        for line in trace:
            if any(error in line for error in ERROR_PATTERNS):
                continue
            for path in PATH_RE.findall(line):
                name = Path(path).name
                toolkit = _TOOLKIT.match(path)
                backend = None
                if (path.startswith('/dev/nvidia') or name.startswith(('libcuda.', 'libnvidia-') + NVIDIA_LIB_PREFIXES)
                        or (toolkit and '/cuda' in toolkit.group(1))):
                    backend = 'nvidia'
                elif (path == '/dev/kfd' or name.startswith(('libamdhip64.', 'libhsa-runtime64.') + AMD_LIB_PREFIXES)
                      or (toolkit and '/rocm' in toolkit.group(1))):
                    backend = 'amd'
                if backend:
                    detected.add(backend)
                    if toolkit and (mode == 'auto' or mode == backend):
                        roots.add(toolkit.group(1))
    return sorted(detected) if mode == 'auto' else [mode], sorted(roots)


def runtime_flags(backends):
    return [RUNTIME_FLAGS[backend] for backend in backends]


def prepare_environment(env_vars):
    """Avoid embedding capture-node GPU visibility; prioritize bound drivers."""
    result = {key: value for key, value in env_vars.items()
              if key not in ALLOCATION_VARIABLES
              and not any(key == prefix + name for prefix in ('SINGULARITYENV_', 'APPTAINERENV_')
                          for name in ALLOCATION_VARIABLES)}
    libs = result.get('LD_LIBRARY_PATH', '')
    result['LD_LIBRARY_PATH'] = ':'.join(
        ['/.singularity.d/libs'] + [p for p in libs.split(':') if p and p != '/.singularity.d/libs'])
    return result


def render_launcher(backends):
    """Render a portable launcher accepting IMAGE followed by COMMAND [ARGS]."""
    flags = ' '.join(runtime_flags(backends))
    return f'''#!/bin/sh
# Generated by DEFCON. Execute within your scheduler's GPU allocation.
set -eu
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 IMAGE COMMAND [ARGS...]" >&2
    exit 2
fi
runtime=${{DEFCON_CONTAINER_RUNTIME:-singularity}}
image=$1
shift
exec "$runtime" exec {flags} "$image" "$@"
'''


def application_libraries(trace_path: Path):
    """Capture successfully accessed GPU application libraries at any location."""
    libraries = set()
    with trace_path.open(errors='ignore') as trace:
        for line in trace:
            if any(error in line for error in ERROR_PATTERNS):
                continue
            for path in PATH_RE.findall(line):
                name = Path(path).name
                if name.startswith(APPLICATION_LIB_PREFIXES) and re.search(r'\.so(?:\.\d+)*$', name):
                    libraries.add(path)
    return sorted(libraries)
