"""Detect MPI workloads and render a host-launched container command."""

from pathlib import Path
import re

from strace_parser import ERROR_PATTERNS, MODULE_INSTALL_RE, PATH_RE

MPI_MODES = ('auto', 'on', 'none')
MPI_MODULES = {'openmpi', 'mvapich2', 'mpich', 'intel-mpi', 'impi'}
MPI_LIBRARY = re.compile(r'^lib(?:mpi|mpich|mpifort|mpi_cxx|mpi_mpifh|pmi|pmix)\.so(?:\.\d+)*$')
MPI_COMMAND = re.compile(r'(?<![\w-])(?:mpirun|mpiexec|srun)(?![\w-])')


def inspect_mpi(trace_path: Path, mode='auto', command_file=None):
    """Return whether MPI is used and any traced module installation roots."""
    if mode not in MPI_MODES:
        raise ValueError(f'Unknown MPI mode: {mode}')
    if mode == 'none':
        return False, []
    detected = False
    roots = set()
    with trace_path.open(errors='ignore') as trace:
        for line in trace:
            if any(error in line for error in ERROR_PATTERNS):
                continue
            for path in PATH_RE.findall(line):
                match = MODULE_INSTALL_RE.match(path)
                if match and Path(match.group(1)).parts[3].lower() in MPI_MODULES:
                    detected = True
                    roots.add(match.group(1))
                if MPI_LIBRARY.match(Path(path).name) or Path(path).name in {'mpirun', 'mpiexec'}:
                    detected = True
    if command_file and Path(command_file).is_file():
        for line in Path(command_file).read_text(errors='ignore').splitlines():
            if not line.lstrip().startswith('#') and MPI_COMMAND.search(line):
                detected = True
                break
    return detected or mode == 'on', sorted(roots)


def prepare_environment(env_vars):
    """Let the current scheduler and MPI launcher supply rank state."""
    return {key: value for key, value in env_vars.items()
            if not key.startswith(('OMPI_', 'PMI_', 'PMIX_', 'SLURM_', 'MPI_LOCALRANKID'))
            and key not in {'MPICH_RANK_REORDER_METHOD', 'HYDRA_PROXY_ID'}}


def render_launcher(gpu_backends=()):
    """Run host mpirun/srun, then a container for each rank."""
    from environments.gpu import runtime_flags

    flags = ' '.join(runtime_flags(gpu_backends))
    return f'''#!/bin/sh
# Generated by DEFCON. Run inside a scheduler allocation with a compatible host MPI.
set -eu
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 IMAGE RANKS COMMAND [ARGS...]" >&2
    exit 2
fi
image=$1
ranks=$2
case "$ranks" in
    ''|*[!0-9]*|0) echo "RANKS must be a positive integer" >&2; exit 2 ;;
esac
shift 2
runtime=${{DEFCON_CONTAINER_RUNTIME:-singularity}}
mpi_launcher=${{DEFCON_MPI_LAUNCHER:-mpirun}}
exec "$mpi_launcher" -n "$ranks" "$runtime" exec {flags} "$image" "$@"
'''
